unsigned char link_Front[] = {
  WHITE, WHITE, WHITE, BLACK, GREEN, GREEN, BLACK, WHITE, WHITE, WHITE, //1
  PINK , WHITE, BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, WHITE, PINK, //2
  BLACK, PINK , BLACK, ORANGE, YELLOW, YELLOW, ORANGE, BLACK, PINK, BLACK, //3
  WHITE, BLACK, ORANGE, YELLOW, PINK, PINK, YELLOW,ORANGE,BLACK,WHITE, //4
  WHITE, BLACK, PINK, BLUE, PINK, PINK, BLUE, PINK, BLACK, WHITE, //5
  BLACK, GREEN, BLACK, PINK, PINK, PINK, PINK, BLACK, GREEN, BLACK, //6
  BLACK, PINK, BROWN, GREEN, GREEN, GREEN, GREEN, BROWN, PINK, BLACK, //7
  PINK, PINK, GREEN, BROWN, YELLOW, YELLOW, BROWN, GREEN, PINK, PINK, //8
  BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, //9
  WHITE, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, WHITE, //10
  WHITE, WHITE, BLACK, BROWN, BLACK, BLACK, BROWN, BLACK, WHITE, WHITE, //11
  WHITE, WHITE, WHITE, BLACK, WHITE, WHITE, BLACK, WHITE, WHITE, WHITE, //12
};

unsigned char link_Back[] = {
  WHITE, WHITE, WHITE, BLACK, GREEN, GREEN, BLACK, WHITE, WHITE, WHITE, //1
  PINK , WHITE, BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, WHITE, PINK, //2
  BLACK, PINK , BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, PINK, BLACK, //3
  WHITE, BLACK, GREEN, BLACK, GREEN, GREEN, BLACK,GREEN,BLACK,WHITE, //4
  WHITE, BLACK, ORANGE, GREEN, BLACK, BLACK, GREEN, ORANGE, BLACK, WHITE, //5
  BLACK, GREEN, BLACK, ORANGE, YELLOW, YELLOW, ORANGE, BLACK, GREEN, BLACK, //6
  BLACK, PINK, BROWN, GREEN, GREEN, GREEN, GREEN, BROWN, PINK, BLACK, //7
  PINK, PINK, GREEN, BROWN, BROWN, BROWN, BROWN, GREEN, PINK, PINK, //8
  BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, //9
  WHITE, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, WHITE, //10
  WHITE, WHITE, BLACK, BROWN, BLACK, BLACK, BROWN, BLACK, WHITE, WHITE, //11
  WHITE, WHITE, WHITE, BLACK, WHITE, WHITE, BLACK, WHITE, WHITE, WHITE, //12
};

unsigned char link_Right[] = {
  WHITE, WHITE, BLACK, BLACK, GREEN, GREEN, BLACK, WHITE, WHITE, WHITE, //1
  PINK , BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, WHITE, WHITE, //2
  BLACK, PINK , BLACK, ORANGE, YELLOW, YELLOW, ORANGE, ORANGE, BLACK, WHITE, //3
  WHITE, BLACK, ORANGE, YELLOW, PINK, PINK, YELLOW,ORANGE,BLACK,WHITE, //4
  WHITE, BLACK, ORANGE, PINK, BLUE, PINK, PINK, BLUE, BLACK, WHITE, //5
  BLACK, GREEN, BLACK, BLACK, PINK, PINK, PINK, PINK, GREEN, BLACK, //6
  BLACK, PINK, BLACK, GREEN, GREEN, GREEN, GREEN, BROWN, PINK, BLACK, //7
  PINK, PINK, BLACK, BROWN, BROWN, YELLOW, YELLOW, GREEN, PINK, BLACK, //8
  BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, WHITE, //9
  WHITE, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, WHITE, //10
  WHITE, WHITE, BLACK, BROWN, BLACK, BLACK, BROWN, BLACK, WHITE, WHITE, //11
  WHITE, WHITE, WHITE, BLACK, WHITE, WHITE, BLACK, WHITE, WHITE, WHITE, //12
};

unsigned char link_Left[] = {
  WHITE, WHITE, WHITE, BLACK, GREEN, GREEN, BLACK, BLACK, WHITE, WHITE, //1
  WHITE , WHITE, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, PINK, //2
  WHITE, BLACK , ORANGE, ORANGE, YELLOW, YELLOW, ORANGE, BLACK, PINK, BLACK, //3
  WHITE, BLACK, ORANGE, YELLOW, PINK, PINK, YELLOW,ORANGE,BLACK,WHITE, //4
  WHITE, BLACK, BLUE, PINK, PINK, BLUE, PINK, ORANGE, BLACK, WHITE, //5
  BLACK, GREEN, PINK, PINK, PINK, PINK, BLACK, BLACK, GREEN, BLACK, //6
  BLACK, PINK, BROWN, GREEN, GREEN, GREEN, GREEN, BLACK, PINK, BLACK, //7
  BLACK, PINK, GREEN, YELLOW, YELLOW, BROWN, BROWN, BLACK, PINK, PINK, //8
  WHITE, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, //9
  WHITE, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, WHITE, //10
  WHITE, WHITE, BLACK, BROWN, BLACK, BLACK, BROWN, BLACK, WHITE, WHITE, //11
  WHITE, WHITE, WHITE, BLACK, WHITE, WHITE, BLACK, WHITE, WHITE, WHITE, //12
};

unsigned char link_FrontsSword[] = {
  WHITE, WHITE, WHITE, BLACK, GREEN, GREEN, BLACK, WHITE, WHITE, WHITE, //1
  PINK , WHITE, BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, WHITE, PINK, //2
  BLACK, PINK , BLACK, ORANGE, YELLOW, YELLOW, ORANGE, BLACK, PINK, BLACK, //3
  WHITE, BLACK, ORANGE, YELLOW, PINK, PINK, YELLOW,ORANGE,BLACK,WHITE, //4
  WHITE, BLACK, PINK, BLUE, PINK, PINK, BLUE, PINK, BLACK, WHITE, //5
  BLACK, GREEN, BLACK, PINK, PINK, PINK, PINK, BLACK, GREEN, BLACK, //6
  BLACK, PINK, BROWN, GREEN, GREEN, GREEN, GREEN, BROWN, PINK, BLACK, //7
  PINK, PINK, GREEN, BROWN, YELLOW, YELLOW, BROWN, GREEN, PINK, PINK, //8
  BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN, BROWN, //9
  WHITE, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, GRAY, WHITE, //10
  WHITE, WHITE, BLACK, BROWN, BLACK, BLACK, BROWN, BLACK, GRAY, WHITE, //11
  WHITE, WHITE, WHITE, BLACK, WHITE, WHITE, BLACK, WHITE, GRAY, WHITE, //12
};

unsigned char link_BackSword[] = {
  WHITE, WHITE, WHITE, BLACK, GREEN, GREEN, BLACK, WHITE, WHITE, WHITE, //1
  PINK , WHITE, BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, WHITE, PINK, //2
  BLACK, PINK , BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, PINK, BLACK, //3
  WHITE, BLACK, GREEN, BLACK, GREEN, GREEN, BLACK,GREEN,BLACK,WHITE, //4
  WHITE, BLACK, ORANGE, GREEN, BLACK, BLACK, GREEN, ORANGE, BLACK, WHITE, //5
  BLACK, GREEN, BLACK, ORANGE, YELLOW, YELLOW, ORANGE, BLACK, GREEN, BLACK, //6
  BLACK, PINK, BROWN, GREEN, GREEN, GREEN, GREEN, BROWN, PINK, BLACK, //7
  PINK, PINK, GREEN, BROWN, BROWN, BROWN, BROWN, GREEN, PINK, PINK, //8
  BROWN, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, //9
  WHITE, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, WHITE, //10
  WHITE, GRAY, BLACK, BROWN, BLACK, BLACK, BROWN, BLACK, WHITE, WHITE, //11
  WHITE, GRAY, WHITE, BLACK, WHITE, WHITE, BLACK, WHITE, WHITE, WHITE, //12
};

unsigned char link_RightSword[] = {
  WHITE, WHITE, BLACK, BLACK, GREEN, GREEN, BLACK, WHITE, WHITE, WHITE,WHITE,WHITE,WHITE,WHITE, //1
  PINK , BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, WHITE, WHITE,WHITE,WHITE,WHITE,WHITE, //2
  BLACK, PINK , BLACK, ORANGE, YELLOW, YELLOW, ORANGE, ORANGE, BLACK, WHITE,WHITE,WHITE,WHITE, //3
  WHITE, BLACK, ORANGE, YELLOW, PINK, PINK, YELLOW,ORANGE,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE, //4
  WHITE, BLACK, ORANGE, PINK, BLUE, PINK, PINK, BLUE, BLACK, WHITE, WHITE, WHITE,WHITE,WHITE, //5
  BLACK, GREEN, BLACK, BLACK, PINK, PINK, PINK, PINK, BLACK, BLACK,BROWN,WHITE,WHITE,WHITE,  //6
  BLACK, PINK, BLACK, GREEN, GREEN, GREEN, GREEN, BROWN, GREEN, PINK, BROWN,GRAY,GRAY,GRAY,//7
  PINK, PINK, BLACK, BROWN, BROWN, YELLOW, YELLOW, GREEN, BLACK, PINK, BROWN,WHITE,WHITE,WHITE,//8
  BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, WHITE, WHITE,WHITE,WHITE,WHITE,//9
  WHITE, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, WHITE, WHITE,WHITE,WHITE,WHITE,//10
  WHITE, WHITE, BLACK, BROWN, BLACK, BLACK, BROWN, BLACK, WHITE, WHITE, WHITE,WHITE,WHITE,WHITE,//11
  WHITE, WHITE, WHITE, BLACK, WHITE, WHITE, BLACK, WHITE, WHITE, WHITE, WHITE,WHITE,WHITE,WHITE,//12
};

unsigned char link_LeftSword[] = {
  WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, GREEN, GREEN, BLACK, BLACK, WHITE, WHITE, //1
  WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, PINK, //2
  WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, ORANGE, ORANGE, YELLOW, YELLOW, ORANGE, BLACK, PINK, BLACK, //3
  WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, ORANGE, YELLOW, PINK, PINK, YELLOW,ORANGE,BLACK,WHITE, //4
  WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, BLUE , PINK, PINK, BLUE, PINK, ORANGE, BLACK, WHITE, //5
  WHITE, WHITE, WHITE, BROWN, BLACK, BLACK, PINK , PINK, PINK, PINK, BLACK, BLACK, GREEN, BLACK, //6
  GRAY , GRAY , GRAY , BROWN, PINK, GREEN , BROWN, GREEN, GREEN, GREEN, GREEN, BLACK, PINK, BLACK, //7
  WHITE, WHITE, WHITE, BROWN, PINK, BLACK , GREEN, YELLOW, YELLOW, BROWN, BROWN, BLACK, PINK, PINK, //8
  WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, //9
  WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, WHITE, //10
  WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, BROWN, BLACK, BLACK, BROWN, BLACK, WHITE, WHITE, //11
  WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, WHITE, WHITE, BLACK, WHITE, WHITE, WHITE, //12
};

//Zelda

unsigned char zelda_Front[] = {
  WHITE, BLACK, WHITE, WHITE, ORANGE, ORANGE, WHITE, WHITE, BLACK, WHITE, //1
  PINK , BLACK, GRAY, YELLOW, YELLOW, YELLOW, YELLOW, GRAY, BLACK, PINK, //2
  BLACK, PINK , BLACK, ORANGE, WHITE, RED, ORANGE, BLACK, PINK, BLACK, //3
  WHITE, BLACK, ORANGE, YELLOW, YELLOW, YELLOW, YELLOW,ORANGE,BLACK,WHITE, //4
  WHITE, ORANGE, PINK, BLUE, PINK, PINK, BLUE, PINK, ORANGE, WHITE, //5
  BLACK, PURPLE, BLACK, PINK, PINK, PINK, PINK, BLACK, PURPLE, BLACK, //6
  BLACK, PINK, YELLOW, PURPLE, PURPLE, PURPLE, PURPLE, YELLOW, PINK, BLACK, //7
  BLUE, BLUE, PURPLE, YELLOW, YELLOW, YELLOW, YELLOW, PURPLE, BLUE, BLUE, //8
  BLACK, BLACK, PURPLE, PURPLE, BLUE, BLUE, PURPLE, PURPLE, BLACK, BLACK, //9
  WHITE, BLACK, PURPLE, PURPLE, BLUE, BLUE, PURPLE, PURPLE, BLACK, WHITE, //10
  WHITE, WHITE, BLACK, PURPLE, BLUE, BLUE, PURPLE, BLACK, WHITE, WHITE, //11
  WHITE, WHITE, WHITE, BLACK, BLACK, BLACK, BLACK, WHITE, WHITE, WHITE, //12
};

unsigned char zelda_Back[] = {
  WHITE, BLACK, WHITE, WHITE, ORANGE, ORANGE, WHITE, WHITE, BLACK, WHITE, //1
  PINK , BLACK, GRAY, YELLOW, YELLOW, YELLOW, YELLOW, GRAY, BLACK, PINK, //2
  BLACK, PINK , BLACK, BLACK, GRAY, GRAY, BLACK, BLACK, PINK, BLACK, //3
  WHITE, BLACK, ORANGE, YELLOW, ORANGE, ORANGE, YELLOW,ORANGE,BLACK,WHITE, //4
  WHITE, ORANGE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, ORANGE, WHITE, //5
  BLACK, PURPLE, BLACK, ORANGE, YELLOW, YELLOW, ORANGE, BLACK, PURPLE, BLACK, //6
  BLACK, PINK, YELLOW, PURPLE, PURPLE, PURPLE, PURPLE, YELLOW, PINK, BLACK, //7
  BLUE, BLUE, PURPLE, YELLOW, YELLOW, YELLOW, YELLOW, PURPLE, BLUE, BLUE, //8
  BLACK, BLACK, PURPLE, PURPLE, BLUE, BLUE, PURPLE, PURPLE, BLACK, BLACK, //9
  WHITE, BLACK, PURPLE, PURPLE, BLUE, BLUE, PURPLE, PURPLE, BLACK, WHITE, //10
  WHITE, WHITE, BLACK, PURPLE, BLUE, BLUE, PURPLE, BLACK, WHITE, WHITE, //11
  WHITE, WHITE, WHITE, BLACK, BLACK, BLACK, BLACK, WHITE, WHITE, WHITE, //12
};

unsigned char zelda_Right[] = {
  WHITE, BLACK, WHITE, WHITE, ORANGE, ORANGE, ORANGE, WHITE, BLACK, WHITE, //1
  PINK , BLACK, GRAY, ORANGE, YELLOW, YELLOW, YELLOW, BLACK, GRAY, WHITE, //2
  BLACK, PINK , BLACK, BLACK, YELLOW, WHITE, RED, ORANGE, BLACK, WHITE, //3
  WHITE, BLACK, ORANGE, YELLOW, YELLOW, YELLOW, YELLOW,YELLOW,BLACK,WHITE, //4
  WHITE, BLACK, ORANGE, PINK, BLUE, PINK, PINK, BLUE, BLACK, WHITE, //5
  BLACK, PURPLE, ORANGE, BLACK, PINK, PINK, PINK, PINK, PURPLE, BLACK, //6
  BLACK, PINK, BLACK, PURPLE, PURPLE, PURPLE, PURPLE, YELLOW, PINK, BLACK, //7
  BLUE, BLUE, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, PURPLE, BLUE, BLACK, //8
  BLACK, BLACK, PURPLE, PURPLE, PURPLE, BLUE, BLUE, PURPLE, BLACK, WHITE, //9
  WHITE, BLACK, BLACK, PURPLE, PURPLE, BLUE, BLUE, PURPLE, BLACK, WHITE, //10
  WHITE, WHITE, BLACK, PURPLE, PURPLE, BLUE, BLUE, BLACK, WHITE, WHITE, //11
  WHITE, WHITE, WHITE, BLACK, BLACK, BLACK, BLACK, WHITE, WHITE, WHITE, //12
};

unsigned char zelda_Left[] = {
  WHITE, BLACK, WHITE, ORANGE, ORANGE, ORANGE, WHITE, WHITE, BLACK, WHITE, //1
  WHITE , GRAY, BLACK, YELLOW, YELLOW, YELLOW, ORANGE, GRAY, BLACK, PINK, //2
  WHITE, BLACK, ORANGE , RED, WHITE, YELLOW, BLACK, BLACK, PINK, BLACK,  //3
  WHITE, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW,ORANGE,BLACK,WHITE, //4
  WHITE, BLACK, BLUE, PINK, PINK, BLUE, PINK, ORANGE, BLACK, WHITE, //5
  BLACK, PURPLE, PINK, PINK, PINK, PINK, BLACK, ORANGE, PURPLE, BLACK, //6
  BLACK, PINK, YELLOW, PURPLE, PURPLE, PURPLE, PURPLE, BLACK, PINK, BLACK, //7
  BLACK, BLUE, PURPLE, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLUE, BLUE, //8
  WHITE, BLACK, PURPLE, BLUE, BLUE, PURPLE, PURPLE, PURPLE, BLACK, BLACK, //9
  WHITE, BLACK, PURPLE, BLUE, BLUE, PURPLE, PURPLE, BLACK, BLACK, WHITE, //10
  WHITE, WHITE, BLACK, BLUE, BLUE, PURPLE, PURPLE, BLACK, WHITE, WHITE, //11
  WHITE, WHITE, WHITE, BLACK, BLACK, BLACK, BLACK, WHITE, WHITE, WHITE, //12
};

//Ganondor
unsigned char Ganondorf_Front[] = {
  WHITE, WHITE, BLACK, WHITE, BLACK, BLACK, WHITE, BLACK, WHITE, WHITE, //1
  GREEN , BLACK, BLACK, YELLOW, RED, RED, YELLOW, BLACK, BLACK, GREEN, //2
  BLACK, GREEN , BLACK, RED, GREEN, GREEN, RED, BLACK, GREEN, BLACK, //3
  WHITE, BLACK, RED, GREEN, BLUE, BLUE, GREEN,RED,BLACK,WHITE, //4
  WHITE, BLACK, GREEN, BROWN, GREEN, GREEN, BROWN, GREEN, BLACK, WHITE, //5
  BLACK, GRAY, BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, GRAY, BLACK, //6
  BLACK, GRAY, BROWN, YELLOW, BLACK, BLACK, YELLOW, BROWN, GRAY, BLACK, //7
  GREEN, GRAY, YELLOW, BROWN, RED, RED, BROWN, YELLOW, GRAY, GREEN, //8
  BLACK, BLACK, GRAY, YELLOW, GRAY, GRAY, YELLOW, GRAY, BLACK, BLACK, //9
  BROWN, BLACK, YELLOW, YELLOW, GRAY, GRAY, YELLOW, YELLOW, BLACK, BROWN, //10
  BROWN, BLACK, BLACK, BROWN, BLACK, BLACK, BROWN, BLACK, BLACK, BROWN, //11
  WHITE, BROWN, BLACK, BROWN, BLACK, BLACK, BROWN, BLACK, BROWN, WHITE, //12
  WHITE, WHITE, BLACK, BLACK, WHITE, WHITE, BLACK, BLACK, WHITE, WHITE, //13
};

unsigned char Ganondorf_Back[] = {
  WHITE, WHITE, BLACK, WHITE, BLACK, BLACK, WHITE, BLACK, WHITE, WHITE, //1
  GREEN , BLACK, BLACK, YELLOW, RED, RED, YELLOW, BLACK, BLACK, GREEN, //2
  BLACK, GREEN , BLACK, RED, YELLOW, YELLOW, RED, BLACK, GREEN, BLACK, //3
  WHITE, BLACK, RED, RED, RED, RED, RED, RED, BLACK,WHITE, //4
  WHITE, BLACK, RED, RED, RED, RED, RED, RED, BLACK, WHITE, //5
  BLACK, GRAY, BLACK, RED, RED, RED, RED, BLACK, GRAY, BLACK, //6
  BLACK, GRAY, BROWN, BROWN, BLACK, BLACK, BROWN, BROWN, GRAY, BLACK, //7
  GREEN, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GREEN, //8
  BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, //9
  BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, //10
  BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, //11
  WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, WHITE, //12
  WHITE, WHITE, BLACK, BLACK, WHITE, WHITE, BLACK, BLACK, WHITE, WHITE, //13
};

unsigned char Ganondorf_FrontSword[] = {
  WHITE, WHITE, BLACK, WHITE, BLACK, BLACK, WHITE, BLACK, WHITE, WHITE, //1
  GREEN , BLACK, BLACK, YELLOW, RED, RED, YELLOW, BLACK, BLACK, GREEN, //2
  BLACK, GREEN , BLACK, RED, GREEN, GREEN, RED, BLACK, GREEN, BLACK, //3
  WHITE, BLACK, RED, GREEN, BLUE, BLUE, GREEN,RED,BLACK,WHITE, //4
  WHITE, BLACK, GREEN, BROWN, GREEN, GREEN, BROWN, GREEN, BLACK, WHITE, //5
  BLACK, GRAY, BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, GRAY, BLACK, //6
  BLACK, GRAY, BROWN, YELLOW, BLACK, BLACK, YELLOW, BROWN, GRAY, BLACK, //7
  GREEN, GRAY, YELLOW, BROWN, RED, RED, BROWN, YELLOW, GRAY, GREEN, //8
  BLACK, BLACK, BLACK, YELLOW, GRAY, GRAY, YELLOW, GRAY, BLACK, BLACK, //9
  BROWN, GRAY, YELLOW, YELLOW, GRAY, GRAY, YELLOW, YELLOW, BLACK, BROWN, //10
  BROWN, GRAY, BLACK, BROWN, BLACK, BLACK, BROWN, BLACK, BLACK, BROWN, //11
  BROWN, GRAY, BLACK, BROWN, BLACK, BLACK, BROWN, BLACK, BROWN, WHITE, //12
  WHITE, GRAY, BLACK, BLACK, WHITE, WHITE, BLACK, BLACK, WHITE, WHITE, //13
};

unsigned char Ganondorf_BackSword[] = {
  WHITE, WHITE, BLACK, WHITE, BLACK, BLACK, WHITE, BLACK, WHITE, WHITE, //1
  GREEN , BLACK, BLACK, YELLOW, RED, RED, YELLOW, BLACK, BLACK, GREEN, //2
  BLACK, GREEN , BLACK, RED, YELLOW, YELLOW, RED, BLACK, GREEN, BLACK, //3
  WHITE, BLACK, RED, RED, RED, RED, RED, RED, BLACK,WHITE, //4
  WHITE, BLACK, RED, RED, RED, RED, RED, RED, BLACK, WHITE, //5
  BLACK, GRAY, BLACK, RED, RED, RED, RED, BLACK, GRAY, BLACK, //6
  BLACK, GRAY, BROWN, BROWN, BLACK, BLACK, BROWN, BROWN, GRAY, BLACK, //7
  GREEN, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GREEN, //8
  BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, //9
  BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, //10
  BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, //11
  WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, WHITE, //12
  WHITE, WHITE, BLACK, BLACK, WHITE, WHITE, BLACK, BLACK, GRAY, WHITE, //13
};

unsigned char Ganondorf_Right[] = {
  WHITE, WHITE, WHITE, BLACK, WHITE, BLACK, BLACK, WHITE, WHITE, WHITE,WHITE,WHITE,WHITE,WHITE, //1
  GREEN , BLACK, RED, BLACK, YELLOW, RED, RED, BLACK, WHITE, WHITE,WHITE,WHITE,WHITE,WHITE, //2
  BLACK, GREEN , BLACK, RED, RED, GREEN, GREEN, RED, BLACK, WHITE,WHITE,WHITE,WHITE,WHITE, //3
  WHITE, BLACK, RED, RED, GREEN, BLUE, BLUE, GREEN, BLACK,WHITE,WHITE,WHITE,WHITE,WHITE, //4
  WHITE, BLACK, RED, GREEN, BROWN, GREEN, GREEN, BROWN, BLACK, WHITE,WHITE,WHITE,WHITE,WHITE, //5
  BLACK, GRAY, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK,BROWN,WHITE,WHITE,WHITE, //6
  BLACK, GRAY, BLACK, BROWN, YELLOW, BLACK, BLACK, YELLOW, GRAY, GRAY,BROWN,GRAY,GRAY,GRAY, //7
  GREEN, GRAY, BLACK, YELLOW, BROWN, RED, RED, BROWN, BLACK, GREEN,BROWN,WHITE,WHITE,WHITE, //8
  BLACK, BLACK, GRAY, GRAY, YELLOW, GRAY, GRAY, YELLOW, BLACK, WHITE,WHITE,WHITE,WHITE,WHITE, //9
  BROWN, BLACK, BLACK, YELLOW, YELLOW, GRAY, GRAY, YELLOW, BLACK, WHITE,WHITE,WHITE,WHITE,WHITE, //10
  BROWN, BROWN, BLACK, BLACK, BROWN, BLACK, BROWN, BLACK, WHITE, WHITE,WHITE,WHITE,WHITE,WHITE, //11
  WHITE, BROWN, BROWN, BLACK, BROWN, BLACK, BROWN, BLACK, WHITE, WHITE,WHITE,WHITE,WHITE,WHITE, //12
  WHITE, WHITE, WHITE, BLACK, BLACK, WHITE, BLACK, BLACK, WHITE, WHITE, WHITE,WHITE,WHITE,WHITE,//13
};

unsigned char Ganondorf_Left[] = {
  WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, BLACK, WHITE,BLACK,WHITE,WHITE,WHITE, //1
  WHITE , WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, RED, RED, YELLOW,BLACK,RED,BLACK,GREEN, //2
  WHITE, WHITE , WHITE, WHITE, WHITE, BLACK, RED, GREEN, GREEN, RED,RED,BLACK,GREEN,BLACK, //3
  WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, GREEN, BLUE, BLUE,GREEN,RED,RED,BLACK,WHITE, //4
  WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, BROWN, GREEN, GREEN, BROWN,GREEN,RED,BLACK,WHITE, //5
  WHITE, WHITE, WHITE, BROWN, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN,BLACK,BLACK,GRAY,BLACK, //6
  GRAY, GRAY, GRAY, BROWN, GRAY, GRAY, YELLOW, BLACK, BLACK, YELLOW,BROWN,BLACK,GRAY,BLACK, //7
  WHITE, WHITE, WHITE, BROWN, GREEN, BLACK, BROWN, RED, RED, BROWN,YELLOW,BLACK,GRAY,GREEN, //8
  WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, YELLOW, GRAY, GRAY, YELLOW,GRAY,GRAY,BLACK,BLACK, //9
  WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, YELLOW, GRAY, GRAY, YELLOW,YELLOW,BLACK,BLACK,BROWN, //10
  WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, BROWN, BLACK, BROWN,BLACK,BLACK,BROWN,BROWN, //11
  WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, BROWN, BLACK, BROWN,BLACK,BROWN,BROWN,WHITE, //12
  WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, BLACK, WHITE, BLACK, BLACK,WHITE,WHITE,WHITE,//13
};